## ASSIGNMENT 2 - LEXICAL SCOPING ##
#
## OVERVIEW ##
#
# Where, from one perspective, there are two functions present here
# (i.e. makeCacheMatrix() and cacheSolve()), the makeCacheMatrix() function
# actually creates an "object" that comprises a number of functions related
# to a given matrix. It creates an object with functions that can perform the 
# following:
#         
#         1. Through x$get(), (where x is a given matrix), it can return
#                 the original matrix
#         2. Through x$setinverse() the matrix's inverse is calculated
#         3. Through x$getinverse(), it returns the matrix's inverse
#         4. Through x$set(), the existing matrix can be modified
# 
# The cacheSolve() function, on the other hand, computes the inverse of the 
# matrix returned by the previous function, makeCacheMatrix(). HOWEVER, due
# to the cache-ing element, if the same matrix's inverse has been calculated
# and (therefore) cached, the cacheSolve() function will return the inverse
# value from the cache directly, as opposed to recalculating the value.
#
## THE FIRST FUNCTION - makeCacheMatrix() ##
#
# As noted in the comments at the top, this function creates a matrix and 
# an object/list of functions that can accomplish the following:
#       1. Through x$get(), (where x is a given matrix), it can return
#               the original matrix
#       2. Through x$setinverse() the matrix's inverse is calculated
#       3. Through x$getinverse(), it returns the matrix's inverse
#       4. Through x$set(), the existing matrix can be modified

makeCacheMatrix <- function(x)
        {
        i <- NULL
        set <- function(y) {
                print("You are now accessing the set() function")
                x <<- y
                i<<- NULL
        }
        get <- function() {
                print ("You are now accessing the get() function")
                x
        }
        setinverse <- function(inverse) {
                print ("You are now accessing the setinverse() function")
        
                i <<- inverse
        }
        getinverse <- function(){ 
                print("You are now accessing the getinverse() function")
                i
        }
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}

## THE SECOND FUNCTION - cacheSolve() ##
# This function calculates the inverse of the matrix object generated by
# the makeCacheMatrix() function. The unique feature of this function is
# that, if the inverse has already been calculated (and the matrix has not 
# changed), then the cachesolve() takes and returns the value stored in the
# cache as opposed to recalculating the inverse of the matrix from scratch.

cacheSolve <- function(x, ...) {
        i <- x$getinverse()
        if(!is.null(i)) {
                message("This value has already been Cached! Retrieving cached data...")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinverse(i)
        i
}